In [6]:
import numpy as np

In [8]:
np1 = np.array([1,2,3,4])

In [9]:
np1

array([1, 2, 3, 4])

In [10]:
type(np1)

numpy.ndarray

In [12]:
Mat1 = np.array([[1,2],[3,4]])

In [13]:
Mat1

array([[1, 2],
       [3, 4]])

In [14]:
type(Mat1)

numpy.ndarray

In [15]:
np1.shape

(4,)

In [16]:
Mat1.shape

(2, 2)

In [17]:
Mat1.dtype

dtype('int64')

In [18]:
np1.dtype

dtype('int64')

In [19]:
Mat1[0][0]=6

In [20]:
Mat1

array([[6, 2],
       [3, 4]])

In [21]:
Mat1[0][1] = 'r'

ValueError: invalid literal for int() with base 10: 'r'

In [22]:
np2 = np.arange(0,10,1)

In [23]:
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np2.shape

(10,)

In [29]:
## 20 Numbers between range -> Linspace
np3 = np.linspace(0,10,20)

In [26]:
np3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
np3.shape

(20,)

In [30]:
## Random Matrix
Mat2 = np.random.rand(5,4)

In [31]:
Mat2

array([[4.57957580e-01, 5.66231230e-04, 9.56233437e-01, 7.26958883e-01],
       [9.36839129e-01, 9.73397677e-01, 1.23981410e-01, 2.67476533e-01],
       [5.44802383e-01, 7.82491944e-01, 5.86698145e-01, 9.28865620e-01],
       [4.84981514e-02, 9.28244627e-01, 4.54879159e-01, 6.34345961e-01],
       [2.90126137e-01, 9.68024389e-01, 1.43345038e-01, 5.35578782e-01]])

In [32]:
## Normally Distributed Random Numbers
Mat3 = np.random.randn(5,4)

In [33]:
Mat3

array([[-0.40665852, -0.9984921 , -0.47865018, -0.06571057],
       [ 0.41422826,  0.88543068,  0.72747697, -0.09788029],
       [-1.16467698,  0.26051851, -0.21221543, -0.36076397],
       [ 0.05990763,  0.95126118,  0.39214462,  0.33739407],
       [ 1.19824053, -0.82522096, -0.84996546,  1.8016609 ]])

In [39]:
## Diagonal Matrix
np4 = np.arange(0,9,1).reshape((3,3))

In [40]:
np4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np4.shape

(3, 3)

In [42]:
np.diag(np4)

array([0, 4, 8])

In [43]:
np.diag(np4,k=1)

array([1, 5])

In [44]:
np.diag(np4,k=-1)

array([3, 7])

In [45]:
np.diag(np.diag(np4))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

In [46]:
np.diag(np.diag(np4,k=1))

array([[1, 0],
       [0, 5]])

In [48]:
np.zeros(4)

array([0., 0., 0., 0.])

In [49]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [50]:
Mat3

array([[-0.40665852, -0.9984921 , -0.47865018, -0.06571057],
       [ 0.41422826,  0.88543068,  0.72747697, -0.09788029],
       [-1.16467698,  0.26051851, -0.21221543, -0.36076397],
       [ 0.05990763,  0.95126118,  0.39214462,  0.33739407],
       [ 1.19824053, -0.82522096, -0.84996546,  1.8016609 ]])

In [51]:
## Slicing on NP Matrix
Mat3[1:,2:]

array([[ 0.72747697, -0.09788029],
       [-0.21221543, -0.36076397],
       [ 0.39214462,  0.33739407],
       [-0.84996546,  1.8016609 ]])